### ISSUE TITLE
ImportError

### ISSUE THREAD

**Issue by Fazik83** [wasilukm/hoymiles_modbus#1]
* hoymiles_modbus version:hoymiles_modbus-0.1.0
* Python version: 3,9
* Operating System: Armbian Bullseye

### Description

python3 client.py
Traceback (most recent call last):
  File "/hoymiles_modbus/hoymiles_modbus/client.py", line 8, in <module>
    from .datatypes import MicroinverterData, PlantData, _serial_number_t
ImportError: attempted relative import with no known parent package

**Comment by wasilukm** [comment]
Thank you for trying to use the code. However, it seems that you are trying to use it incorrectly. It is not a stand alone script but a library which can be used in some other project. Please check documentation to see how to install it and use  https://wasilukm.github.io/hoymiles_modbus/
