### ISSUE TITLE
Unable to communicate with my DTU-Lite-S

### ISSUE THREAD

**Issue by Toug19** [wasilukm/hoymiles_modbus#25]
* hoymiles_modbus version:0.5.0
* Python version: 3.7.3
* Operating System: Ubuntu (Raspbian)

### Description

I'm trying to get the power delivered by my solar panels through the DTU-Lite-S.
I'm trying to connect to the DTU then get information. But seems that the connection failed.

### What I Did
pi@raspberrypi:~ $  :python3
Python 3.7.3 (default, Jun 29 2023, 18:03:57) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from hoymiles_modbus.client import HoymilesModbusTCP
>>> plant_data=HoymilesModbusTCP('192.168.1.155').plant_data
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/pi/.local/lib/python3.7/site-packages/hoymiles_modbus/client.py", line 136, in plant_data
    microinverter_data = self.microinverter_data
  File "/home/pi/.local/lib/python3.7/site-packages/hoymiles_modbus/client.py", line 110, in microinverter_data
    with self._get_client() as client:
  File "/home/pi/.local/lib/python3.7/site-packages/pymodbus/client/sync.py", line 120, in __enter__
    raise ConnectionException("Failed to connect[%s]" % (self.__str__()))
pymodbus.exceptions.ConnectionException: Modbus Error: [Connection] Failed to connect[ModbusTcpClient(192.168.1.155:502)]

**Comment by wasilukm** [comment]
Unfortunately this type of DTU is not supported by this tool as it doesn't expose modbus.

**Comment by Toug19** [comment]
Thanks. I managed to get the info using https://github.com/suaveolent/hoymiles-wifi.

**Comment by wasilukm** [comment]
Thank you for sharing this interesting project
