### ISSUE TITLE
Getting S/N and Port #

### ISSUE THREAD

**Issue by ccolumbu999** [wasilukm/hoymiles_modbus#27]
Hi wasilukm,
I have a HoyMiles install and I have been playing with the ModBus TCP directly.
I figured out how to get the S/N and Port numbers from the data.
Here is how I did it.
You need values 0-3, convert each of them to binary. Zero pad so they are length 16.
So now you will have 4 values that look like this: 0000110000010001
Concatenate them together so you have something like this:
0000110000010001000011000001000100001100000100010000110000010001
Next split them into chunks of 4 so you have:
[0] = 0000
[1] = 1100
[2] = 0001
[3] = 0001
. . . 
[15] = 0001
Convert chunks 2-13 to decimal and you will have the S/N, convert chunk 15 to decimal and you will have the port #.
Please let me know if you have any questions, I hope this helps so you can include S/N + Port in a future version.

**Comment by wasilukm** [comment]
Hi,

The interface already offers S/N and port number: https://wasilukm.github.io/hoymiles_modbus/api/#hoymiles_modbus.datatypes.InverterData
Is there anything specific missing?
