### ISSUE TITLE
Make unit ID configurable 

### ISSUE THREAD

**Issue by ArekKubacki** [wasilukm/hoymiles_modbus#6]
Is it possible to make unit ID configurable? Unfortunately I have to change to another one.

**Comment by wasilukm** [comment]
Are you thinking about DTU or microinverter serial number? I'm not sure what would you expect. Updating/replacing modules shall be done by the instalator in the Hoymiles application. This library is not meant to manage this, only to show data from DTU. I haven't testest this but I would assume when a microinverter is added, removed, or replaced this will be naturally reflected by the library without any additional action.

**Comment by ArekKubacki** [comment]
Hello,
I need to change modbus ID in this line:

`result = client.read_holding_registers(start_address, count, unit=1)`

I have got unit id 105. I want to use rs485 port and convert Modbus RTU to Modbus TCP.

**Comment by wasilukm** [comment]
Interesting, haven't you consider using rs485 directly? Support for rs485 could be added to the library. I don't have rs485 hardware, so it will be hard for me to develop and verify this. Perhaps you could propose a change.

Regarding unit ID, this should be easily doable. I will try to add support for custom unit ID in a few days.

**Comment by ArekKubacki** [comment]
Unfortunately, at my home I already have a ModbusRTU to ModbusTCP converter installed. 
I would have to specially route the ModbusRTU cable form DTU to PC.

It seems to me that making this change takes a few lines of code. I would be grateful for a quick change :)

I want to check this connection because I heard that DTU works more stable via RS485.

**Comment by wasilukm** [comment]
Out of curiosity, what kind of converter are you using?

**Comment by ArekKubacki** [comment]
I use 
https://www.waveshare.com/RS232-485-TO-ETH.htm

At first it only worked with an air conditioner. Now also DTU is added.

**Comment by wasilukm** [comment]
@ArekKubacki please check release 0.4.0. It would be beneficial for other users if you could share your observation about stability of your setup in the issue #4
