### ISSUE TITLE
Why do I feel like there is no option to use this with basic auth? I have to provide username and passowrd to get to my dtu.

### ISSUE THREAD

**Issue by SyncHot** [wasilukm/hoymiles_modbus#8]
* hoymiles_modbus version:
* Python version:
* Operating System:

### Description

Describe what you were trying to get done.
Tell us what happened, what went wrong, and what you expected to happen.

### What I Did

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```

**Comment by wasilukm** [comment]
This library works only on ModbusTCP protocol. This protocol doesn't support any authentication so neither the library. Maybe you are thinking about http?

**Comment by SyncHot** [comment]
Sorry, this is so right. Is there a way to actually be able to connect this to energy dashboard in home assistant?

**Comment by wasilukm** [comment]
Try https://github.com/wasilukm/hoymiles-mqtt
