### ISSUE TITLE
DTU statibility

### ISSUE THREAD

**Issue by adam-kulagowski** [wasilukm/hoymiles_modbus#9]
* hoymiles_modbus version: latest
* Python version: 3.10.4
* Operating System: Linux ubuntu 22.04

### Description

I'm getting lots of errors:

`pymodbus.exceptions.ModbusIOException: Modbus Error: [Input/Output] Modbus Error: [Invalid Message] No response received, expected at least 8 bytes (0 received)`

around 90% of communication attempts ends w/ above error. Event simple query for DTU S/N

### What I Did

```
python3
Python 3.10.4 (main, Jun 29 2022, 12:14:53) [GCC 11.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from hoymiles_modbus.client import HoymilesModbusTCP
>>> HoymilesModbusTCP('192.168.20.67').dtu
'10f880162915'
>>> HoymilesModbusTCP('192.168.20.67').dtu
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/fidor/.local/lib/python3.10/site-packages/hoymiles_modbus/client.py", line 100, in dtu
    result = self._read_registers(client, 0x2000, 3, self._unit_id)
  File "/home/fidor/.local/lib/python3.10/site-packages/hoymiles_modbus/client.py", line 74, in _read_registers
    raise result
pymodbus.exceptions.ModbusIOException: Modbus Error: [Input/Output] Modbus Error: [Invalid Message] No response received, expected at least 8 bytes (0 received)
```

While I understand that DTU leaves much to be desired I've found a workaround that make usability a little bit betterL

In `hoymiles_modbus/client.py` I've changed the line 68 to look like this:
```
        return ModbusTcpClient(self._host, self._port, framer=_CustomSocketFramer, timeout=3, retry_on_empty=True, close_comm_on_error=True, strict=False, reconnect_delay=1000)
```
Above extra parameters seems to be helping (not making the connection better but forcing the retry to hide the issue). Maybe those options can be included in Your library?

**Comment by wasilukm** [comment]
Sure, I can add the parameters but I have doubts if all of them are necessary. I would rather limit the number of parameters to avoid unexpected behaviors.
Are you able to check if `retry_on_empty` is enough?

**Comment by adam-kulagowski** [comment]
I'll try to limit the parameters and get back to You. 
Currently the DTU-PRO is offline as it permanently keeps open access point (no password) which is serious security issue for me.

**Comment by adam-kulagowski** [comment]
This seems to be the best in terms of performance and stability:
```
        return ModbusTcpClient(self._host, self._port, framer=_CustomSocketFramer, timeout=2, retry_on_empty=True, reconnect_delay=1000)
```

**Comment by wasilukm** [comment]
@adam-kulagowski  please check 0.5.0 version where I've added a property to set additional communication parameters https://wasilukm.github.io/hoymiles_modbus/api/#hoymiles_modbus.client.HoymilesModbusTCP.comm_params

**Comment by adam-kulagowski** [comment]
I've returned the DTU and switched to OpenDTU ( https://github.com/tbnobody/OpenDTU ) in the meantime, as the supplier did not provide fix for open AP in my DTU - sorry :/

**Comment by wasilukm** [comment]
@adam-kulagowski that's understandable. I'm also considering OpenDTU, it seems to be quite a good alternative.
